### ISSUE TITLE
null value from ANTLR is not handled, for expressions like "eval x" or "eval x*2"

### ISSUE THREAD

**Issue by wixette** [aha-001/SeedLang#45]
1) Start SeedLang.Shell, enter "eval x\n":

The returned node of parser.single_stmt() contains a null field: node.Expr = null. Meanwhile localCollection.Diagnostics.Count is still 0. The outer logic treated this as a normal case and continued the execution. The output from the shell is:

```
eval
```

2) Start SeedLang.Shell, enter "eval x+2\n":

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SeedLang.Ast.BaseValue.op_Addition(BaseValue lhs, BaseValue rhs) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Ast/BaseValue.cs:line 25

**Comment by codingpotato** [comment]
Fixed by commit #47
